# Generated by Django 5.0.3 on 2026-10-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_timeout_minutes',
            field=models.PositiveIntegerField(default=10, verbose_name='مهلت پرداخت نوبت (دقیقه)'),
        ),
    ]
