# Generated by Django 5.2.17 on 2026-09-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_doctoravailability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkingSchedule',
        ),
    ]
