# Generated by Django 5.0.3 on 2026-09-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
