# Generated by Django 5.0.3 on 2026-10-07 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_doctoravailability_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='availability',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.doctoravailability'),
        ),
    ]
